logging:
  out_path: out/temporal/kq_and_gr/grid_search/test
  save_keys: null 
  grid_search:
    seed: 0
    n_samples: 1
  history:
    record: True
  kqgr:
    eval: 'last-random'
    tau: 3
model:
  input_layer:
    w_bi: identity
    w_ir: identity
    encoding: base2
    features: 2
    redundancy: [10, 15, 20] 
    resolution: 10 # affects how redundancy is applied 
    chunk_size: 10 # set to resolution 
    interleaving: 0
    pertubation: override
    w_in: null
  output_layer:
    activation: sigmoid
    n_outputs: 1
  reservoir_layer:
    init: zeros
    k_avg: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    k_min: 0
    k_max: 25
    mode: [homogeneous, heterogeneous]
    n_nodes: 500
    p: 0.5
    reset: true
    self_loops: null
  training:
    accuracy_threshold: 0.5
    batch_size: 100
    criterion: BCE
    epochs: 40
    evaluation: dev
dataset: # this whole section is repurposed to control the custom experiments
  task: density # not really just using the x values and ignoring y
  bits: 10
  window: 3 # not using this
  delay: 1 # not using this
  split: # not training the model, just recording state changes with input
    train: 1
    dev: 0
    test: 0
  samples: 1 # overwritten by code so we get samples equal to number of reservoir nodes (square matrix) * number of models seeds (each model gets a set)
  seed: 0