logging:
  out_path: out/temporal/kq_and_gr/grid_search/test
  save_keys: null 
  grid_search:
    seed: 0
    n_samples: 1
  history:
    record: True
  kqgr:
    eval: 'last-random'
    tau: 3
model:
  input_layer:
    w_bi: identity
    w_ir: identity
    encoding: base2
    features: 2
    redundancy: 1
    resolution: 10 # affects how redundancy is applied 
    chunk_size: 10 # set to resolution 
    interleaving: 0
    pertubation: override
    w_in: null
  output_layer:
    activation: sigmoid
    n_outputs: 1
  reservoir_layer:
    init: zeros
    k_avg: [1, 2, 3, 4, 5]
    k_min: 0
    k_max: 25
    mode: [homogeneous, heterogeneous]
    n_nodes: 512
    p: 0.5
    reset: true
    self_loops: null
  training:
    accuracy_threshold: 0.5
    batch_size: 100
    criterion: BCE
    epochs: 40
    evaluation: dev
dataset:
  train:
    task: density 
    bits: 10
    window: 3
    delay: 1
    split:
      train: 0.5
      dev: 0.5
      test: 0
    samples: 2048 # 2**10=1024 input combinations, twice this ensures a copy for train/dev
    sampling_mode: 'exhaustive'
  kqgr:
    bits: 10
    split:
      train: 1
      dev: 0
      test: 0
    sampling_mode: 'exhaustive'
    tau: 3
    evaluation: 'last'