# grid_search -> single_run: 'single_run' in out_path, set evaluation=test, set record_history=true
# df = pd.read_hdf('/out/temporal/density/grid_search/homogeneous-deterministic/log.h5', 'df')
# df[(df['accuracy'] < 0.85) & (df['accuracy'] > .8)]['params'].apply(lambda p: p.model)
# out/temporal/density/grid_search/homogeneous-deterministic/runs/2025_05_09_014400_078455/checkpoints/2025_05_09_014405_021874
dataset:
  bit_stream_length: 10
  generate_data: false
  samples: 1000
  seed: 30
  split:
    dev: 0.3
    test: 0.3
    train: 0.4
  tao: 0
  task: density
  window_size: 3
logging:
  grid_search:
    n_samples: 10
    seed: 0
  history:
    buffer_size: 64
    record_history: true
  out_path: out/temporal/density/single_run/homogeneous-deterministic-sample_model
  train_log:
    accuracy: 0.7519198664440735
    epoch: 40
    loss: 0.3657870590686798
model:
  input_layer:
    w_ir: out-1:1:1
    w_bi: identity
    encoding: base2
    features: 10
    chunk_size: 1
    interleaving: 0
    n_nodes: 5
    pertubation: override
    redundancy: 1
    resolution: 1
    seed: 1541552926
    w_in: null
  output_layer:
    activation: sigmoid
    n_outputs: 1
    seed: 1541552926
  reservoir_layer:
    init: zeros
    k_avg: 10.0
    k_max: 4
    k_min: 4
    mode: homogeneous
    n_nodes: 10
    p: 0.5
    reset: true
    seed: 0
    self_loops: null
  training:
    accuracy_threshold: 0.5
    batch_size: 100
    criterion: BCE
    drop_last: true
    epochs: 4
    evaluation: test
    seed: 1541552926
    shuffle: true
