model:
  input_layer:
    seed: 0
    pertubation: 'xor'
    encoding: binary_embedding
    features: 2
    bits_per_feature: 48
    redundancy: 6
    interleaving: 1
  output_layer:
    n_outputs: 2
    seed: 531
  reservoir_layer:
    init: zeros
    k_avg: 2.1
    k_max: 6
    n_nodes: 3000
    p: 0.5
    seed: 531
    self_loops: 0.0
  training:
    batch_size: 100
    criterion: 'MSE'
    epochs: 100
    learning_rate: 0.001
    accuracy_threshold: 0.05
    evaluation: 'test' 
    seed: 531
logging:
  out_path: 'out/path_integration/single_run/2D/good_model'
  history:
    record_history: true
    buffer_size: 64
dataset:
  dimensions: 2
  steps: 5
  strategy_config:
    type: LevyFlightStrategy
    params:
      alpha: 3
      momentum: 0.9
      bias: 0
  boundary_config:
    type: PolygonBoundary
    params:
      n_sides: 12
      radius: 0.5
      rotation: 0 
  split:
    train: 0.4
    dev: 0.3
    test: 0.3
  samples: 10000
  seed: 0