model:
  input_layer:
    pertubation: 'override'
    encoding: binary_embedding
    features: 1
    resolution: 8
    redundancy: 3
    chunk_size: 24 
    seed: 5
  output_layer:
    n_outputs: 1
    seed: 5
  reservoir_layer:
    mode: heterogeneous
    init: zeros
    k_avg: 2.2
    k_max: 25
    n_nodes: 1000
    p: 0.5
    self_loops: 0.0 # note that this seems critical? why?
    seed: 5 
  training:
    batch_size: 100
    epochs: 100
    accuracy_threshold: 0.05
    evaluation: 'test' 
    seed: 0
logging:
  out_path: 'out/path_integration/single_run/1D/good_model'
  # history:
  #   record_history: true
  #   buffer_size: 64
dataset:
  dimensions: 1
  steps: 5
  strategy:
    name: LevyFlightStrategy
    alpha: 1
    momentum: 0.0
    step_size: 0.05
  boundary:
    name: IntervalBoundary
  split:
    train: 0.5
    dev: 0.3
    test: 0.2
  samples: 20000
  seed: 0