logging:
  out_path: 'out/path_integration/2D/single_run/design_choices/test2'
  history:
    record_history: true
model:
  input_layer:
    w_bi: identity
    w_ir: out-3:3:1 # Iâ†’R mapping: deterministic out-degree
    pertubation: override
    encoding: base2
    features: 2
    resolution: 3
    redundancy: 2
    chunks: 2 
    interleaving: 1
    seed: 0
  output_layer:
    n_outputs: 2
    seed: 0
  reservoir_layer:
    init: zeros
    k_avg: 3.0
    k_min: 0
    k_max: 25
    mode: homogeneous
    n_nodes: 30
    p: 0.5
    reset: true
    self_loops: null
    seed: 0
  training:
    accuracy_threshold: 0.05
    batch_size: 100
    criterion: MSE
    epochs: 4
    evaluation: dev
    seed: 0
dataset:
  dimensions: 2
  steps: 5
  strategy:
    name: LevyFlightStrategy
    params:
      alpha: 1
      momentum: 0.0
      step_size: 0.05
  boundary:
    name: PolygonBoundary
    params:
      n_sides: 12
      radius: 1.0
      rotation: pi/4
  split:
    train: 0.5
    dev: 0.3
    test: 0.2
  samples: 20000
  seed: 0