model:
  input_layer:
    pertubation_strategy: 'xor'
    encoding: 'binary_embedding'
    n_inputs: 2
    resolution: 8
    redundancy: [1, 2, 3, 4, 5, 6]
    interleaving: 0
  reservoir_layer:
    n_nodes: [1000, 2000, 3000, 4000, 5000]
    k_avg: [1.8, 1.9, 2, 2.1, 2.2]
    k_max: 6
    p: .5
    self_loops: [0, .2, .4, .6, .8, 1]
    init: ['zeros', 'random']
  output_layer:
    n_outputs: 2
  training:
    batch_size: 100
    epochs: 40
    radius_threshold: 0.05
    learning_rate: 0.001
    evaluation: 'dev' 
logging:
  out_path: '/out/grid_search/2D/initial_sweep2'
  grid_search:
    seed: 0
    n_samples: 10