model:
  input_layer:
    encoding: 'binary_embedding'
    n_inputs: 2
    bits_per_feature: 48
    redundancy: 6
    interleaving: 1
  reservoir_layer:
    n_nodes: 2000
    k_avg: 2 
    k_max: 6
    p: 0.5
    self_loops: 0
    init: 'random' 
  output_layer:
    n_outputs: 2
  training:
    seed: 0
    batch_size: 100
    epochs: 100
    radius_threshold: 0.1
    learning_rate: 0.001
logging:
  out_path: '/out/single_run/2D/good_model'