logging:
  out_path: 'out/path_integration/grid_search/2D/3_steps/homogeneous-stochastic'
  grid_search:
    seed: 0
    n_samples: 25
  save_keys: [parameters]
model:
  input_layer:
    w_bi: identity
    w_ir: [out-0:b:1/b, out-1:b:1/b] # Iâ†’R mapping: stochastic out-degree
    pertubation: [override, xor]
    encoding: base2
    features: 2
    resolution: 8
    redundancy: 6
    chunk_size: 96 
    interleaving: 1
  output_layer:
    n_outputs: 2
  reservoir_layer:
    init: [zeros, random]
    k_avg: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
    k_min: 0
    k_max: 25
    mode: homogeneous
    n_nodes: 3000
    p: 0.5
    reset: true
    self_loops: null
  training:
    accuracy_threshold: 0.05
    batch_size: 100
    criterion: MSE
    epochs: 40
    evaluation: dev
dataset:
  dimensions: 2
  steps: 3
  strategy:
    name: LevyFlightStrategy
    alpha: 1
    momentum: 0.0
    step_size: 0.05
  boundary:
    name: PolygonBoundary
    n_sides: 12
    radius: 1.0
    rotation: pi/4
  split:
    train: 0.5
    dev: 0.3
    test: 0.2
  samples: 20000
  seed: 0