logging:
  out_path: 'out/path_integration/grid_search/1D/homogeneous-deterministic'
  grid_search:
    seed: 0
    n_samples: 25
  save_keys: [parameters]
model:
  input_layer:
    distribution: identity
    connection: [out-1:1:1, out-2:2:1, out-3:3:1] # Iâ†’R mapping: deterministic out-degree
    pertubation: [override, xor]
    encoding: base2
    features: 1
    resolution: 8
    redundancy: 3
    chunk_size: 24 
  output_layer:
    n_outputs: 1
  reservoir_layer:
    init: [zeros, random]
    k_avg: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
    k_min: 0
    k_max: 25
    mode: homogeneous
    n_nodes: 1000
    p: 0.5
    reset: true
    self_loops: null
  training:
    accuracy_threshold: 0.05
    batch_size: 100
    criterion: MSE
    epochs: 40
    evaluation: dev
    learning_rate: 0.001
dataset:
  dimensions: 1
  steps: 5
  strategy:
    type: LevyFlightStrategy
    alpha: 1
    momentum: 0.0
    step_size: 0.05
  boundary:
    type: IntervalBoundary
    radius: 1.0
  split:
    train: 0.5
    dev: 0.3
    test: 0.2
  samples: 20000
  seed: 0
