model:
  input_layer:
    w_bi: 1:1:1:d
    pertubation: 'xor'
    encoding: 'binary_embedding'
    features: 1
    resolution: 8
    redundancy: [1, 2, 3, 4, 5, 6]
    interleaving: 0
  reservoir_layer:
    n_nodes: [1000, 2000, 3000, 4000, 5000]
    k_avg: [2.15, 2.20, 2.25, 2.30, 2.35]
    k_max: 6
    p: .5
    self_loops: [0, .2, .4, .6, .8, 1]
    init: 'random'
  output_layer:
    n_outputs: 1
  training:
    batch_size: 100
    epochs: 40
    accuracy_threshold: 0.05
    evaluation: 'dev' 
logging:
  out_path: 'out/path_integration/grid_search/1D/initial_sweep'
  grid_search:
    seed: 0
    n_samples: 10
dataset:
  path: 'data/path_integration/d-1/s-LevyFlightStrategy/b-IntervalBoundary/n-5/m-10000/r-0/dataset.pt'