logging:
  history:
    buffer_size: 64
    record_history: true
  out_path: out/single_run/temporal/parity/good_model
model:
  input_layer:
    bits_per_feature: 1
    dataset: data/temporal/parity/u-10/w-3/t-1/m-6000/r-0/dataset.pt
    encoding: base2
    interleaving: 0
    n_inputs: 1
    pertubation: xor
    redundancy: 1
    resolution: 1
    seed: 0
  output_layer:
    activation: sigmoid
    n_outputs: 1
    seed: 8
  reservoir_layer:
    init: random
    k_avg: 1.0
    k_max: 20
    k_min: 0
    n_nodes: 500
    p: 0.5
    reset: true
    seed: 8
    self_loops: null
  training:
    accuracy_threshold: 0.5
    batch_size: 100
    criterion: BCE
    epochs: 100
    evaluation: test
    learning_rate: 0.001
    seed: 8
