# grid_search -> single_run: 'single_run' in out_path, set evaluation=test, set record_history=true
dataset:
  bit_stream_length: 10
  generate_data: false
  path: data/temporal/parity/u-10/w-3/t-7/m-6000/r-0/dataset.pt
  samples: 6000
  seed: 1731666172
  split:
    dev: 0.3
    test: 0.3
    train: 0.4
  tao: 7
  task: parity
  window_size: 3
logging:
  grid_search:
    n_samples: 10
    seed: 0
  history:
    buffer_size: 64
    record_history: true
  out_path: out/single_run/temporal/parity/good_model
  train_log:
    accuracy: 1.0
    epoch: 40
    loss: 0.002228794153779745
model:
  input_layer:
    bits_per_feature: 1
    distribution: identity
    connection: out-0:b:1/(a+b)
    encoding: base2
    interleaving: 0
    features: 10
    n_nodes: 10
    pertubation: override
    redundancy: 1
    resolution: 1
    seed: 1731666172
    w_in: null
  output_layer:
    activation: sigmoid
    n_outputs: 1
    seed: 1731666172
  reservoir_layer:
    init: random
    k_avg: 6.0
    k_max: 20
    k_min: 0
    mode: heterogenous
    n_nodes: 500
    p: 0.5
    reset: true
    seed: 1731666172
    self_loops: null
  training:
    accuracy_threshold: 0.5
    batch_size: 100
    criterion: BCE
    drop_last: true
    epochs: 40
    evaluation: test
    learning_rate: 0.001
    seed: 1731666172
    shuffle: true