model:
  input_layer:
    dataset: '/data/path_integration/2D/levy_walk/n_steps/square_boundary/dataset.pt'
    pertubation: 'xor'
    encoding: 'binary_embedding'
    n_inputs: 2
    bits_per_feature: 48
    redundancy: 6
    interleaving: [0, 1]
  reservoir_layer:
    n_nodes: [3000]
    k_avg: [1.8, 1.9, 2, 2.1, 2.2]
    k_max: [6]
    p: [.5]
    self_loops: [0, 0.1, 0.2, 0.3, 0.4, .5, .6, .7, .8, .9, 1]
    init: ['zeros', 'random', 'random_lut_state']
  output_layer:
    n_outputs: 2
  training:
    batch_size: 100
    epochs: 40
    accuracy_threshold: 0.05
    learning_rate: 0.001
    evaluation: 'dev' 
logging:
  out_path: '/out/grid_search/path_integration/2D/initial_sweep'
  grid_search:
    seed: 0
    n_samples: 5