model:
  input_layer:
    dataset: 'data/path_integration/d-2/s-LevyFlightStrategy/b-PolygonBoundary/n-5/m-10000/r-0/dataset.pt'
    pertubation: 'xor'
    bits_per_feature: 48
    encoding: binary_embedding
    interleaving: 0
    n_inputs: 2
    redundancy: 6
    seed: 312
  output_layer:
    n_outputs: 2
  reservoir_layer:
    init: random_lut_state
    k_avg: 2
    k_max: 6
    n_nodes: 3000
    p: 0.5
    self_loops: 0.3
  training:
    batch_size: 100
    epochs: 3
    learning_rate: 0.001
    accuracy_threshold: 0.05
    evaluation: 'test' 
    seed: 0
logging:
  out_path: '/tmp/boolean_reservoir/out/single_run/path_integration/2D/test'
