model:
  input_layer:
    encoding: 'binary_embedding'
    n_inputs: 1
    bits_per_feature: 48
    redundancy: 6
  reservoir_layer:
    n_nodes: 1000
    k_avg: 2.4
    k_max: 6
    p: 0.45
    self_loops: 0
    init: 'random' 
  output_layer:
    n_outputs: 1
  training:
    seed: 3
    batch_size: 100
    epochs: 50
    radius_threshold: 0.05
    learning_rate: 0.001
logging:
  out_path: '/out/single_run/1D/good_model'