model:
  input_layer:
    encoding: 'binary_embedding'
    n_inputs: 1
    bits_per_feature: 48
    redundancy: 6
  reservoir_layer:
    n_nodes: [1000]
    k_avg: [2, 2.2, 2.4, 2.6, 2.8]
    k_max: [5, 6, 7, 8, 9]
    p: [0.35, 0.4, 0.45, 0.5, 0.55]
    self_loops: [0, 0.1, 0.2, 0.3, 0.4]
  output_layer:
    n_outputs: 1
  training:
    batch_size: 100
    epochs: 40
    radius_threshold: 0.05
    learning_rate: 0.001
logging:
  out_path: '/out/grid_search/1D/initial_sweep'
  grid_search:
    seed: 42
    n_samples: 5
  history:
    record_history: False
    history_buffer_size: 10000