model:
  input_layer:
    encoding: 'binary_embedding'
    n_inputs: 1
    bits_per_feature: 48
    redundancy: 6
  reservoir_layer:
    n_nodes: 1000
    k_avg: 2
    k_max: 6
    p: 0.5
    self_loops: [0, 0.1]
    init: 'random' 
  output_layer:
    n_outputs: 1
  training:
    batch_size: 100
    epochs: 40
    radius_threshold: 0.05
    learning_rate: 0.001
logging:
  out_path: '/out/grid_search/1D/test_sweep'
  grid_search:
    seed: 42
    n_samples: 2
  history:
    record_history: False
    history_buffer_size: 10000