name: boolean_reservoir
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - annotated-types=0.6.0=py312h06a4308_0
  - atk-1.0=2.36.0=ha1a6a79_0
  - blas=1.0=mkl
  - blosc=1.21.3=h6a678d5_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py312ha883a20_0
  - brotli=1.0.9=h5eee18b_9
  - brotli-bin=1.0.9=h5eee18b_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - c-blosc2=2.12.0=h80c7b02_0
  - ca-certificates=2024.12.31=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - contourpy=1.3.1=py312hdb19cb5_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.4.1=0
  - cudatoolkit=11.8.0=h6a678d5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - expat=2.6.4=h6a678d5_0
  - filelock=3.13.1=py312h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h55d465d_3
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.51.0=py312h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gdk-pixbuf=2.42.10=h5eee18b_1
  - geos=3.10.6=h6a678d5_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gobject-introspection=1.78.1=py312h42194e9_1
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h78213b7_2
  - gtk2=2.24.33=h73c1081_2
  - gts=0.7.6=hb67d8dd_3
  - harfbuzz=4.3.0=hf52aaf7_2
  - hdf5=1.12.1=h2b7332f_3
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py312h06a4308_1
  - joblib=1.4.2=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - kiwisolver=1.4.4=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurl=8.11.1=hc9e6f67_0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgd=2.3.3=h695aa2c_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.30=0
  - libnvfatbin=12.4.127=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libpng=1.6.39=h5eee18b_0
  - librsvg=2.56.3=h056759b_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=hffd6297_1
  - libtool=2.4.6=h6a678d5_1009
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.13.5=hfdd30dd_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=h7b6447c_2
  - markupsafe=2.1.3=py312h5eee18b_1
  - matplotlib-base=3.10.0=py312hbfdbfaf_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_2
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - mpmath=1.3.0=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.3=py312h06a4308_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.10.1=py312h3c60e43_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - packaging=24.2=py312h06a4308_0
  - pandas=2.2.3=py312h6a678d5_0
  - pango=1.50.7=h05da053_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.0.0=py312hcea889d_1
  - pip=24.2=py312h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - plotly=5.24.1=py312he106c6f_0
  - poppler=24.09.0=hcf11d46_1
  - poppler-data=0.4.11=h06a4308_1
  - py-cpuinfo=9.0.0=py312h06a4308_0
  - pydantic=2.10.3=py312h06a4308_0
  - pydantic-core=2.27.1=py312h4aa5aa6_0
  - pyparsing=3.2.0=py312h06a4308_0
  - pytables=3.10.1=py312h387d6ec_0
  - python=3.12.8=h5148396_0
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-graphviz=0.20.1=py312h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=2.5.1=py3.12_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - readline=8.2=h5eee18b_0
  - scikit-learn=1.5.2=py312h6a678d5_0
  - scipy=1.14.1=py312hc5e2394_0
  - seaborn=0.13.2=py312h06a4308_0
  - setuptools=75.1.0=py312h06a4308_0
  - shapely=2.0.6=py312h6f81d3c_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.3=py312h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=9.0.0=py312h06a4308_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tk=8.6.14=h39e8969_0
  - torchtriton=3.1.0=py312
  - tqdm=4.66.5=py312he106c6f_0
  - typing-extensions=4.12.2=py312h06a4308_0
  - typing_extensions=4.12.2=py312h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py312h5eee18b_1
  - wheel=0.44.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zlib-ng=2.0.7=h5eee18b_0
  - zstd=1.5.6=hc292b87_0
prefix: /opt/conda/envs/boolean_reservoir
